export default interface UserPermissions {
    createImage: boolean,
    readImage: boolean,
    modifyImage: boolean,
    deleteImage: boolean,
    readRenditions: boolean,
    createRenditions: boolean,
    modifyRenditions: boolean,
    deleteRenditions: boolean,
    readProject: boolean,
    createProject: boolean,
    modifyProject: boolean,
    deleteProject: boolean,
    readUser: boolean,
    createUser: boolean,
    modifyUser: boolean,
    deleteUser: boolean,
    publish: boolean,
    publishAll: boolean,
    accessAllProjects: boolean,
}

export const UserPermissionsKeyToNameMapping: { [key in keyof UserPermissions]: string } = {
    createImage: 'Create Image',
    readImage: 'Read Image',
    modifyImage: 'Modify Image',
    deleteImage: 'Delete Image',
    readRenditions: 'Read Renditions',
    createRenditions: 'Create Renditions',       
    modifyRenditions: 'Modify Renditions', 
    deleteRenditions: 'Delete Renditions', 
    readProject: 'Read Project',
    createProject: 'Create Project',
    modifyProject: 'Modify Project',
    deleteProject: 'Delete Project',
    readUser: 'Read User',
    createUser: 'Create User',
    modifyUser: 'Modify User',
    deleteUser: 'Delete User',
    publish: 'Publish',
    publishAll: 'Publish All',
    accessAllProjects: 'Access All Projects',
};

