CREATE TABLE USER_ROLE (
    ID TINYINT UNSIGNED,
    ROLE_NAME VARCHAR(32),
    
    CREATE_IMAGE BOOLEAN,
    READ_IMAGE BOOLEAN,
    MODIFY_IMAGE BOOLEAN,
    DELETE_IMAGE BOOLEAN,
    
    READ_RENDITIONS BOOLEAN,
    CREATE_RENDITIONS BOOLEAN,
    MODIFY_RENDITIONS BOOLEAN,
    DELETE_RENDITIONS BOOLEAN,
    
    READ_PROJECT BOOLEAN,
    CREATE_PROJECT BOOLEAN,
    MODIFY_PROJECT BOOLEAN,
    DELETE_PROJECT BOOLEAN,
    
    READ_USER BOOLEAN,
    CREATE_USER BOOLEAN,
    MODIFY_USER BOOLEAN,
    DELETE_USER BOOLEAN,
    
    PUBLISH BOOLEAN,
    
    PUBLISH_ALL BOOLEAN,
    ACCESS_ALL_PROJECTS BOOLEAN,

    PRIMARY KEY (ID)
);

CREATE TABLE USER (
    ID SMALLINT UNSIGNED,
    LOGIN_ID VARCHAR(16) UNIQUE,
    EMAIL VARCHAR(128) UNIQUE,
    PASSWORD VARCHAR(160),
    NAME VARCHAR(64) NULL,
    USER_ROLE TINYINT UNSIGNED,
    LAST_LOGIN_ON DATETIME NULL,
    CREATED_BY SMALLINT UNSIGNED DEFAULT 0,
    MODIFIED_BY SMALLINT UNSIGNED DEFAULT 0,
    CREATED_ON DATETIME DEFAULT NOW(),
    MODIFIED_ON DATETIME DEFAULT NULL,

    PRIMARY KEY (ID),
    --FOREIGN KEY (USER_ROLE) REFERENCES USER_ROLE(ID)
);

CREATE TABLE PROJECT (
    ID SMALLINT UNSIGNED AUTO_INCREMENT,
    NAME VARCHAR(32),
    SLUG VARCHAR(32),
    DESCRIPTION VARCHAR(256),
    RESTRICT_USERS BOOLEAN DEFAULT FALSE,
    CREATED_BY SMALLINT UNSIGNED DEFAULT 0,
    MODIFIED_BY SMALLINT UNSIGNED DEFAULT 0,
    CREATED_ON DATETIME DEFAULT NOW(),
    MODIFIED_ON DATETIME DEFAULT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE USER_PROJECT (
    USER_ID SMALLINT UNSIGNED,
    PROJECT_ID SMALLINT UNSIGNED,
    
    PRIMARY KEY (USER_ID, PROJECT_ID),
    -- FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE FOLDER (
    ID SMALLINT UNSIGNED AUTO_INCREMENT,
    TITLE VARCHAR(128),
    SLUG VARCHAR(128) UNIQUE,
    PROJECT_ID SMALLINT UNSIGNED,
    DESCRIPTION VARCHAR(256) DEFAULT NULL,
    PARENT_FOLDER_ID SMALLINT UNSIGNED DEFAULT NULL,
    CREATED_BY SMALLINT UNSIGNED DEFAULT 0,
    MODIFIED_BY SMALLINT UNSIGNED DEFAULT 0,
    CREATED_ON DATETIME DEFAULT NOW(),
    MODIFIED_ON DATETIME DEFAULT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IMAGE (
    ID INT UNSIGNED AUTO_INCREMENT,
    ORIGINAL_FILENAME VARCHAR(1000),
    TITLE VARCHAR(256),
    HEIGHT SMALLINT UNSIGNED DEFAULT 0,
    WIDTH SMALLINT UNSIGNED DEFAULT 0,
    ENCODING TINYINT UNSIGNED DEFAULT 40,
    PUBLISHED BOOLEAN DEFAULT NULL,
    PROJECT_ID SMALLINT UNSIGNED,
    FOLDER_ID SMALLINT UNSIGNED DEFAULT NULL,
    CREATED_BY SMALLINT UNSIGNED DEFAULT 0,
    MODIFIED_BY SMALLINT UNSIGNED DEFAULT 0,
    CREATED_ON DATETIME DEFAULT NULL,
    MODIFIED_ON DATETIME DEFAULT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IMAGE_RENDITION (
    ID INT UNSIGNED AUTO_INCREMENT,
    IMAGE_ID INT UNSIGNED,
    HEIGHT SMALLINT UNSIGNED DEFAULT 0,
    WIDTH SMALLINT UNSIGNED DEFAULT 0,
    ENCODING TINYINT UNSIGNED DEFAULT 40,
    TARGET_DEVICE VARCHAR(16) DEFAULT NULL,
    SLUG VARCHAR(256) UNIQUE,
    PUBLISHED BOOLEAN DEFAULT FALSE,
    CREATED_BY SMALLINT UNSIGNED DEFAULT 0,
    MODIFIED_BY SMALLINT UNSIGNED DEFAULT 0,
    CREATED_ON DATETIME DEFAULT NOW(),
    MODIFIED_ON DATETIME DEFAULT NULL,

    PRIMARY KEY (ID),
    UNIQUE KEY (IMAGE_ID, SLUG),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
);
